"use strict";
const bcrypt = require("bcrypt");
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Users",
      [
        {
          wins: 0,
          losses: 0,
          name: "Витя",
          email: "1@1",
          password: await bcrypt.hash("1", 10),
          avatar: "http://obrazovaka.ru/wp-content/uploads/2014/08/Ak-47.jpg",
          isAdmin: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Петя",
          email: "2@2",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Коля",
          email: "3@3",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Катя",
          email: "4@4",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Маша",
          email: "5@5",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Вася",
          email: "6@6",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Саша",
          email: "7@7",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Наташа",
          email: "8@8",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Миша",
          email: "9@9",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Ваня",
          email: "10@10",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Дима",
          email: "11@11",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Даша",
          email: "12@12",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Аня",
          email: "13@13",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Лена",
          email: "14@14",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Таня",
          email: "15@15",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Маша",
          email: "16@16",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { wins: 0,
          losses: 0,
          name: "Ваня",
          email: "17@17",
          password: await bcrypt.hash("1", 10),
          avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png",
          isAdmin: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Users", null, {});
  },
};
